name: Deploy Onyx Screen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout latest code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 3. Build project
      - name: Build Project
        run: npm run build
        env:
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
          VITE_APP_ADMIN_ID: ${{ secrets.VITE_APP_ADMIN_ID }}
          VITE_APP_SOCKET_SECRET_KEY: ${{ secrets.VITE_APP_SOCKET_SECRET_KEY }}

      # 4. Clean and prepare Onyx folder
      - name: Clean and prepare Onyx folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/TV_Screens/Onyx
            sudo mkdir -p /var/www/html/TV_Screens/Onyx
            sudo chown -R ubuntu:ubuntu /var/www/html/TV_Screens/Onyx
            sudo chmod -R 755 /var/www/html/TV_Screens/Onyx

      # 5. Upload new build
      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/TV_Screens/Onyx"
          overwrite: true
          strip_components: 1

      # 6. Restart Nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
